# Generated by Django 4.1.7 on 2023-04-03 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='data_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
