# Generated by Django 4.1.7 on 2023-04-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_data_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='course_ID',
        ),
    ]
