# Generated by Django 4.1.7 on 2023-04-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_course_id_course_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
